server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jwt_test #change this to your database url
    password: letting #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect